language: php

php:
 - 5.4
 - 5.6
 - 6.0
 - 7.0
 - "hhvm"
 
before_script:
 - php jelloff run:install composer *listed

script: php jelloff run:tests core

matrix:
 fast_failure:true

notifications:
 on_success: never
 on_failure: always

branches:
  only:
    - master